# Generated by Django 5.1.4 on 2025-03-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_profile_email_token_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
