# Generated by Django 5.1.4 on 2025-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_active',
            field=models.BooleanField(default=False),
        ),
    ]
