# Generated by Django 5.1.4 on 2025-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('forgot_password_token', models.CharField(blank=True, max_length=200, null=True)),
                ('is_email_active', models.BooleanField(default=False)),
                ('email_verification_expiry', models.DateTimeField(blank=True, null=True)),
                ('forgot_password_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
