# Generated by Django 5.1.4 on 2025-04-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customuser_delete_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='forgot_password_token',
            new_name='forget_password_token',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='forgot_password_token_expiry',
            new_name='forget_password_token_expiry',
        ),
    ]
