# Generated by Django 5.1.4 on 2025-04-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_forgot_password_token_customuser_forget_password_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
